#+STARTUP: align fold hidestars indent

* Decision to make about advertising

We have two choices:

1. Advertisers pay the system and the money is destroyed, no moderator nor a
   node recieves anything.
2. Advertisers pay moderators and money is not destroyed.

** Option 1: destruction of money by ads

*** Advantages

Supposedly moderators lose their incentives to sell their money because they
don't receive any in the first place.

*** Disadvantages

1. Moderators will not search for advertisers.
2. Because of (1) you must enforce a system that inserts ads even if
   moderators don't want to or are not able to find advertisers.
3. Because of (2) users become molested by ads not in relation to the content.
4. Bad advertisers and spammers will insert ads which might be even illegal or
   annoying.
5. Moderators cannot avoid (1),(2),(3),(4) unless they insert fake ads and pay the system
   as if they were advertisers. This would kill the trust in the entire Bitcloud.
6. Because of (5) most people won't want to be a moderator, as they won't be
   able to find proper advertisers and don't want to pay.
7. Because of (6) nodes won't also become moderators, as they lose the money
   the earn by bandwidth sharing.
8. People will switch to alternative p2p protocols with real moderation or
   free of ads.

** Option 2: Advertisers pay moderators

*** Advantages

1. Moderators will search for advertisers to earn money.
2. Ads will be relevant to the content.
3. Moderators earn money that they can hold or exchange.
4. Free content is possible because paid content pays moderators for the
   rest. And anyway, nodes can select moderators, which means that they can
   select themselves if they are also moderators. This means that nodes can
   select paid only moderators, and choose if they want dedicate some of their
   space to free content or not.
   
*** Disadvantages

I don't see any, but Kyle insists that moderators are irrevocably going to sell
their coins immediately after they have paid, making the system to crash. I
need to see serious proof of this.

* Decision to make about mixing moderators and nodes

If we mix moderators and nodes, it will have the following problems:

1. Someone willing to do moderation must be a technical guy and manage a
   node. This means managing an entire server and be aware of security risks,
   pay the bill for the ISP, etc.
2. You must introduce another complexity: collections of node pools that act
   together to provide some content. This will complicate the protocol a lot.
3. Because of (2) you centralize power in the nodes.
4. Because of (3) there will be copiers. Other nodes will try to copy the most
   successful nodes.
5. Because of 4, if primary node goes down, all the copiers go down.
6. Because of (4) if a node deletes everything all the copiers must follow.

** Ethical reasons

There is really not a good reason to mix moderators and nodes. Moderators are
the base for a nice thin layer which will facilitate things to everyone.
By making imposible for a moderator to select a node, you ensure that any node
can attach to a moderator, and the human behind the moderation service knows
that nodes are going to follow him if he provides good content. In fact, he
will desire that nodes follow him.

** Economic reasons

The same cannot be said when a node and a moderator are not the same. Because
of the way that the protocol is going to be constructed, it would be easier
for the node to create a kind of apartheid for nodes trying to copy him.

Why he would do so? *Because by banning copiers he can absorb most of the
bandwidth for the content he is hosting*.

