#+STARTUP: align fold hidestars indent

* Decision on the economic and business setup of Bitcloud.

We have two choices:

1. Advertisers pay into the system and the money is destroyed, no moderator nor a
   node recieves anything.
2. Advertisers pay moderators and money is not destroyed.

** Option 1: destruction of money by ads

*** Advantages

There aren't really any huge advantages to this system. The problem is that the mediacoins currency and network integrity is harmed with the other setup. - Kyle

*** Disadvantages

1. Moderators will not search for advertisers.
2. Because of (1) you must enforce a system that inserts ads even if
   moderators don't want to or are not able to find advertisers.
3. Because of (2) users become molested by ads not in relation to the content.
4. Bad advertisers and spammers will insert ads which might be even illegal or
   annoying.
5. Moderators cannot avoid (1),(2),(3),(4) unless they insert fake ads and pay the system
   as if they were advertisers. This would kill the trust in the entire Bitcloud.
6. Because of (5) most people won't want to be a moderator, as they won't be
   able to find proper advertisers and don't want to pay.
7. Because of (6) nodes won't also become moderators, as they lose the money
   the earn by bandwidth sharing.
8. People will switch to alternative p2p protocols with real moderation or
   free of ads.
   
**** Responses from Kyle:
1. This is not necesarily a huge problem. An interface can be placed into the
   Bitcloud software so advertisers can bid on ad space in different
   channels/categories. I would also personally tell other people that they
   can advertise on WeTube/Bitcloud. I'm sure I wouldn't be the only one as
   everyone who owns mediacoins would benefit from advertisers bidding higher
   prices for ad space. This isn't really a problem that causes any systemic
   risk to the Bitcloud network.
   - Javier: you can't control the interface. The day 2 there will be a
     version of the Wetube interface with an adblock like feature removing the
     bid thing.
     - Kyle: The interface I'm talking about doesn't display ads. It's the section of
       the interface strictly for advertisers who wish to purchase ad space. The actual
       ads are embedded in the videos.
2. This is true. Unless I am able to think of an alternative, all advertising
   decisions will be made by all of the Bitcloud nodes put together rather
   than individual moderators.
   - Javier: Every node is going to serve different things. There is no posible
     consensus on whom to admit as advertisers. Sex ads cannot be shown in
     non-sex content, for example, but you can apply this to every discipline.
3. As mentioned in part one, of this response, advertisers would be able to
   bid on ad space for particular channels, so the ads would still be related
   to the content.
   - Javier: forget about this. This is open source and that part can be very
     easily removed. You cannot force the interface to do this things.
4. I've thought of this issue as well and will need to find a solution.
5. 
6. Since nodes are moderating themselves, moderation still takes place. I'm
   not sure I understand this argument.
   - Javier: that makes things even worse, because now not only you prevent
     people for being moderators, but also to be nodes!
7. One solution to this could be default channels/categories in the protocol
   instead of nodes creating their own categories. I'd have to think about
   others if that solution was not preferred.
   - Javier: very bad idea, moderators should be able to create their own
     categories or the system will be very inflexible. For example, a news
     moderation should be able to create categories about news types.
8. An alternative protocol built in the form of Option 2 could still pop up, but obviously I think it would fail due to the same problems related to the value of the currency and network stability. It should also be noted that videos could be uploaded for free in option 1, but ads would need to be placed on the video once they received a certain number of views.

While a few of these disadvantages are legitimate, they still don't compare to the disadvantage in option 2 where the entire network is unstable becaue the value of mediacoins is not tied to the number of users on the network.

** Option 2: Advertisers pay moderators

*** Advantages

1. Moderators will search for advertisers to earn money.
2. Ads will be relevant to the content.
3. Moderators earn money that they can hold or exchange.
4. Free content is possible because paid content pays moderators for the
   rest. And anyway, nodes can select moderators, which means that they can
   select themselves if they are also moderators. This means that nodes can
   select paid only moderators, and choose if they want dedicate some of their
   space to free content or not.
   
****   Responses from Kyle
1. As mentioned in my response to this as a disadvantage in option 1, this is not a serious issue. Advertisers can still bid up prices for ad space in the "Advertise on WeTube" tab on the WeTube software client.
2. This applies to both options.
3. I'm not sure how this is an advantage. I look at it as a disadvantage
   because a certain percentage of moderators will sell their mediacoins for
   some other currency. It hurts the growth of mediacoins as a currency
   because money will be going into the system and then back out of it instead
   of just staying in the system. It is similar to someone buying bitcoins in
   one country to send to a friend in another country. That friend sells the
   bitcoins when he receives them. Money went in, but then it went back out,
   so there is no increased value for bitcoins, the currency.
   - Javier: and what is the problem of that in bitcoin? Bitcoin is a way to
     pay, our system will to. *NOTE*: an advertiser has to *buy* money from
     nodes before they can pay to the moderators. When a buy happens, our coin
     raise in value. Yes, then the moderator may or may not sell the money. If
     it sells, price of our coin *compensates* because the money to pay
     moderators was increased before. If they hold, price increases.
4. Free content is still possible in option 1. Content can be uploaded by
   users for free, but ads will be added once a certain video or other files
   starts to require a lot of bandwidth. Allowing unlimited uploads for free
   without ads is a recipe for disaster because everyone would just choose
   that option. No current video host offers this option because they would go
   bankrupt.
   - Javier: it is absolutetly not a disaster because in this system
     moderators are REALLY motivated to find advertisers. *AND*, as I told
     you, a node can ALWAYS choose their moderators, so they can choose a
     moderator that inserts ads.
   
*** Disadvantages

I don't see any, but Kyle insists that moderators are irrevocably going to sell
their coins immediately after they have paid, making the system to crash. I
need to see serious proof of this.

**** Response from Kyle:
In option 2, the value of the currency is not directly tied to the number of
users who require bandwidth on the network. The problem with this is that the
network will falter greatly when the price of mediacoins crashes due to
speculation. For example, when the price of bitcoin crashes (which it has on
many occasions), miners stop mining because it is no longer profitable for
them to do so. This lowers the pace at which new bitcoins enter the
market. This helps bring the price back up over time. The same is true of the
Bitcloud network, but the problem is that the integrity of the network relies
on nodes staying online. Since the price of mediacoins is not directly tied to
the number of users on Bitcloud, speculators could crash the price (like what
happens with Bitcoin), and then more nodes would go offline because it is no
longer profitable for them to share bandwidth on the Bitcloud network. This
means that there is much less bandwidth on the network as a whole, and users
will notice a lot of lag on the network. If the price of mediacoins is not
directly tied to the number of users on the network (like in option 1), then
it is only a matter of time before this problem takes place. We can't have
nodes going offline because of a price crash because then the users will not
trust Bitcloud to have content available at all times.


The real disadvantage of option 2 is that the network simply doesn't work with
this setup. There are a few extremely minor downsides of switching over the
option 1, but it's much better than having a network that is unstable.

***** Javier:
I think you are confusing terms. I'll try to do my best to
explain it clearly, point by point:
1. It is false that in option 2 the value of the currency is not directly tied
   to the number of users. You should explain why is that, as I haven't heard
   a good analysis on why is that.
   The value of the currency is absolutely determined by the amount of users
   in the network, because of the following:
   Each generated block has a fixed amount of coins. For example, 100 coins
   per block. That means that if more users enter into the system, then more
   nodes must be run and more bandwidth must be shared. The more nodes there
   are, the less they can earn, so prices must go up for our currency.
   No node is going to sell below the price of real bandwidth.
   - Kyle:
     What you describe assumes that the nodes are the only ones selling
      mediacoins at any one time. That's not how it works in reality. This is 
      like saying that bitcoin miners control the price of bitcoin. Once there 
      are a large number of mediacoins in circulation, the holders of those 
      mediacoins control the market because there are many more of them than there 
      are nodes. If the network runs for two years at 100 mediacoins per block, that 
      means there will be over 10.5 million mediacoins in circulation. When there are
      those many coins out there, the nodes don't have much say on what the market price
      is going to be for mediacoins.
2. You can never avoid speculation. Never, never, never. Your system doesn't
   avoid speculation at all.People are free to buy and sell. What we can is
   control the speculation to make the system grow. How? By the intrinsic
   value of our network, and the services that provide our workers (mostly
   moderators).  We have *more* intrinsic value than Bitcoin, because we
   provide a *real* service beyond just being a currency.
   - Kyle:
      Providing extra value during the mining process does not mean anything. If 
      that were true, Primecoin and Peercoin would have more value than Bitcoin. What
      gives a coin value is its utility. This is why no one cares about Primecoin 
      finding prime numbers or Peercoin saving energy costs. You can't avoid 
      speculation, but you can put a floor on the price.
3. Our system is going to be a mix between a currency and an stock market and
   there are good reasons to hold *both*. For example, when people hold Apple
   stocks is because they believe that Apple is doing well. Apple is not
   crashing because they are backed up by the products they sell. We are going
   to be backed up by the services we provide.
   - Kyle:
      This is false. A DAC needs to be a stock/commodity first. If it becomes 
      a currency, that is something for the market to decide. Option 2 does not 
      back up the mediacoins currency with the WeTube service because they are 
      not directly connected because nodes won't control the market price at a 
      certain point as mentioned in the response to point 1.
   In addition to that, we are a currency too, a medium for people to
   interchange goods and services, and we can maintain even a better
   equilibrium than Bitcoin just because we are also backed up by the services
   we provide.
   - Kyle:
      Saying the currency is backed up by our services and actually backing up 
      the currency with the services are two different things. As I've explained 
      many times, the currency is not backed up by the services because the nodes 
      don't have control over the price at a certain point.
4. You assume that moderators are going to sell. Why? You're unable to give
   good answer except your biased opinion.
   - Kyle:
      You assume that moderators are going to hold. Why? You're unable to give a 
      good answer except your biased opinion.
5. *Even if all moderators sell everything in the moment they are paid (a very
   improbable thing), our system still can run STABLE*. Why? Because before a
   moderator can sell, he must first have received a payment. And who is the
   one who pays? The advertiser. And who is the one who sell our coins to
   advertisers? The nodes.
   - Kyle:
      As pointed out in other responses, this assumes nodes are the majority of the 
      market, which they are not. They are at the beginning, but they lose their 
      control of the market over time as more mediacoins are created. Just like with
      bitcoin miners.
   *SO IT COMPENSATES*
   Note that there is a buy and a sell. Advertisers buy, moderators sell, so
   there is an equilibrium. And meanwhile the prices increases because more users
   and nodes come to the system.
   - Kyle:
     Same answer as above. The price does not increase because nodes don't control 
     the price after a certain point in time.

* Decision to make about mixing moderators and nodes

If we mix moderators and nodes, it will have the following problems:

1. Someone willing to do moderation must be a technical guy and manage a
   node. This means managing an entire server and be aware of security risks,
   pay the bill for the ISP, etc.
2. You must introduce another complexity: collections of node pools that act
   together to provide some content. This will complicate the protocol a lot.
3. Because of (2) you centralize power in the nodes.
4. Because of (3) there will be copiers. Other nodes will try to copy the most
   successful nodes.
5. Because of 4, if primary node goes down, all the copiers go down.
6. Because of (4) if a node deletes everything all the copiers must follow.

Response from Kyle:
I will response to this section in the future.

** Ethical reasons

There is really not a good reason to mix moderators and nodes. Moderators are
the base for a nice thin layer which will facilitate things to everyone.
By making imposible for a moderator to select a node, you ensure that any node
can attach to a moderator, and the human behind the moderation service knows
that nodes are going to follow him if he provides good content. In fact, he
will desire that nodes follow him.

Response from Kyle:
I will response to this section in the future.

** Economic reasons

The same cannot be said when a node and a moderator are not the same. Because
of the way that the protocol is going to be constructed, it would be easier
for the node to create a kind of apartheid for nodes trying to copy him.

Why he would do so? *Because by banning copiers he can absorb most of the
bandwidth for the content he is hosting*.

Response from Kyle:
I will response to this section in the future.

