* Description

Warning: I'm not an economist so probably the terminology here is not fully
correct. This is just a proposal and, in case of being accepted in the general
sense, an economist should rewrite it.

My proposal is to construct an entire micro-economy based on virtual services.

Major group participants:

- Node miners. They "print" the money.
- Publishers. They categorize and moderate the content. Equivalent to
  publishers.
- Users. They download and/or pay for the content.
- Authors. They are the users that upload free/paid content.

Services:

- Free bandwidth.
- Free non-guaranteed storage.
- Paid guaranteed storage.
- Paid content (user pays to download).
- Free content.
- Advertising.
- Name registration and resolution.
- Free moderation.
- Paid moderation.

So the whole idea is to give value to our coin by providing good quality
services.

* The user chooses between advertising or paid content

Our main model of income is from advertisement.

Most users in most places will chose not to pay for the content, but there is
no economy if all is free. Someone at some point must introduce a form of
income.

So we introduce advertisement for free content, and remove it if the user pays
for the raw original content.

Advertisement is hardcoded into the content, so the final user can't cheat the
system by installing an ad-block plugin in their clients interface.

Advertisers pay to publishers and nodes are enforced to insert the ads into
the content. The first node to attend the request receives a commission for
inserting the ads, and the rest of the nodes follow.

The advertising market of bitcloud is going to be auto-regulated. Actual humans
-advertisers- contact with other humans -publishers- and trade. They put the
price and the conditions. No enforcement is made by the system itself.
This is the *only* way to provide quality advertisement.

All nodes that store the content with ads are also rewarded with a commission
for it. This way, we ensure that transactions are done within cloudcoins and
that the node is motivated to actually do the work of inserting the ads. Also
will mean that nodes are going to be in the search for good quality publishers
with good conditions and a good rate of commission/quality. In that case, the
disavantage to use an external coin for trades between advertisers and
publishers is that publisher cannot ensure a proper redistribution of its
content, which could ultimately mean low quality of service - if there are
many viewers of a certain content and the publisher hasn't got enough nodes
attached that could mean that those nodes could become saturated. That is not
in the interest of any publisher.

Publishers trying to abuse by advertising too much, will not be chosen by
users. Ads will be always relevant to the content shown, because advertisers
will not choose publishers that provide content that they are not interested
in.

* Analogy for paid content

Some users will not want ads, so they pay for the content.

Lets compare Bitcloud with the industry of book selling.

- Users are the customers.
- Publishers are the publishers.
- Node storage system represent the bookstore.
- Node miners represent the bankers.
- Node law enforces represent the government.

So when a customer enters into a bookstore, the first we observe is that
entering into the store is FREE. If a bookstore charges money for entrance,
customers will be reluctant to enter. Equivalence: we always offer free
bandwidth so we can effectively broadcast the real business here: the rest of the
services. Note that the bookstore actually has to pay for the building,
electricity, workers, etc. They compensate the expenses by earning a
commission in the goods they sell. We compensate free bandwidth by the other
services we offer and also by mining hardware.

Now, in the business chain, one step up, we find publishers. Publishers ensure
a good quality selection of books. They are aligned with certain ideas and
reject low quality books and/or non-aligned to those ideals. They receive a
commission and in exchange they boost the reputation of the books they
promote. Equivalence: we have publishers, they select, categorize, and provide
a face and an opportunity for the content to be broadcasted in accordance with
their ideals and quality requirements, and they receive a commission for
so. Our publishers *will* provide *quality* content being searched by
the user.

Note: if you look at actual p2p systems, specially Kademlia (eMule), the
result of searches are a total mess. Repeated content, corrupted content, fake
content, incorrectly categorized content, illegal content, etc. We want to
avoid that. Publishers will avoid that because they are actually humans
looking for quality.

An important thing to take in count: publishers do *not* need to moderate all
the content that arrives to the system. They just go and search for content in
other publishers or in the unmoderated area, and accept content from
users. Author users must look for good publishers before they try to upload
anything, and request acceptance to the publishers, just like a book author
request acceptance from a publisher.

In case that an user cannot find a publisher, he is always free to become one
by himself and ask nodes for acceptance. In the ultimate case that no node
accepts him, he can setup a new node.

Now, talking about the bookstores, they *store* books. For so they need the
space and resources. They earn a commission on sells because they had the
space there available for the books, so users can physically retrieve
them. Equivalence: node storage system. Users can retrieve content stored in
the nodes. Nodes receive a commission on sells they store.

In addition, nodes may store not only commissioned content, but also
guarantied content, being the equivalent of the store renter for the local.
The difference between guarantied content and not guarantied content is that
guarantied content is paid at periodical intervals and nodes are enforced by
the bitcloud law to actually make sure that the content is always
available. Non guarantied content may or may not stay in the node depending on
technical requirements. For example, when the node runs out of storage space
they may remove the less solicited content out of their hard disk.

Now, there is an important point: bookstores are completely free to choose
what publishers do they want to sell. They don't want to indiscriminately
full their store with random books. They are forced to do a good selections of
publishers, otherwise his business can crack. Customers are not going to buy
anything they don't want. Most customers would not buy illegal things
either. Equivalence: in our system, nodes are completely free to choose what
publishers to be attached to.

In the real world, there are banks and gold miners. Banks generate the
necessary money for the economy to be a viable thing in function of what
governments allow them. Gold miners exchange the gold they mine with their
work for dollars. Because it is so expensive to mine gold, it is very
valuable. Equivalence: providing bandwidth is expensive, so nodes mine coins
in relation to it. After mining, nodes trade the generated coins for other
services with other workers in the system, or just exchange it for dollars (or
bitcoins).

Usually, the coins mined are sold to customers coming from other
currencies. Value of our coin is directly dependent on the services we
provide. The best services we provide, the more customers are going to enter
in our system. The more customers enter in our system, the more is in the
interest of companies to enter our system.

We have a huge real potential in every single industrial field related to
content providing. We can easily attract film industries, music industries,
game industries, ISPs, advertisers, news agencies, non-profit organizations,
individual artists and much more. Possibilities are so huge that are almost
unimaginable at this point. We are going to change the entire copyright
industry forever.  Most importantly, I think we are going to find a solution
that can mitigate the actual friction between companies and actual humans.

We are also constructing a *virtual market*. A place in which information can
be freely traded without restriction or censorship.

* Free service

In addition to paid content and content with ads, we are of course offering
free services. Publishers have the liberty to choose what content is free.

Most individual users will prefer free content without ads, but chances are
that it is going to be difficult to find a reputable publisher that accepts
their content without condition. In the ultimate case, users not wanting ads
in their content can perfectly choose to setup a node themselves. That will be
the case of many non-profit organizations.

That is perfectly ok, because those free-only nodes at least are providing
bandwidth and encouraging the well wealth of the entire system. They are also
earning money by mining, so they can cover expenses.

* Blockchain

The blockchain is to be decided here, please have a look, read all the options and add your owns:

https://github.com/wetube/bitcloud/blob/master/bitcloud-decisions.org
