#+SEQ_TODO: TO-THINK TO-IMPROVE FINISHED
#+TITLE: *Bitcloud FAQ*
#+OPTIONS: H:7 num:nil toc:t \n:nil stat:nil timestamp:nil html-postamble:nil inline-images:t
#+STARTUP: align fold hidestars
#+LANGUAGE: en

# COMMENT FROM JAVIER: I recommend you to put this in your ~/.emacs:
# (electric-indent-mode +1)
# you can also run it in the current session by
# typing "M-x electric-indent-mode"
# that will facilitate the use of TABs and indentation
# you can also customize org-mode behavior by typing:
# M-x customize-group ENTER org
# also, as you see I have put many options for this file which will facilitate
# your work.
# Please remove this comment.

* FINISHED Q: Why do we need Bitcloud?

A: There are many different cloud-based services out there these days,
but they are all developed in a centralized manner. You have to go to
YouTube to watch your videos, Soundcloud to listen to your music, and
Dropbox or another proprietary cloud storage company to store your
files. Bitcloud allows anyone to create their own cloud based
applications in ways that improve privacy and prevent censorship. The
increased decentralization of Bitcloud also allows for more
competition in the cloud services market. For example, artists can get
a bigger cut of advertising revenue when they post their videos on
WeTube (a future Bitcloud service) rather than YouTube because there
are no overhead expenses.

* TO-IMPROVE Q: What are Cloudcoins?

A: Cloudcoins are the currency of Bitcloud. They are mined by nodes
who host all of the data stored in the Bitcloud network. [X NUMBER OF
COINS] new cloudcoins are mined every [X NUMBER OF MINUTES], and they
are distributed evenly based on the amount of bandwidth shared by each
node during that period of time. (See the decisions document for more 
about missing amounts). Cloudcoins are also used to pay for
the various applications on top of Bitcloud. Whether you want to
purchase advertising space on WeTube or you need to buy some extra
cloud storage, you will have to pay for everything using Cloudcoins.
Cloudcoins are created and spent within Bitcloud. They are not meant as a 
new virtual currency to be used outside of Bitcloud.

* TO-IMPROVE Q: What is WeTube? 

A: WeTube will likely be the first application built on top of
Bitcloud. It will be used as a user interface for an online video
streaming services, similar to YouTube. Artists will be able to upload
videos to various Bitcloud nodes, and they can receive mediacoins from
advertisements placed on their videos or other forms of media. It is
likely that they will be able to earn a larger piece of the pie when
uploading to WeTube rather than other options.

* TO-IMPROVE Q: Is Bitcloud Anonymous?

A: We will provide for the option for Bitcloud to become anonymous by hiding
user information as well as IP address.

* TO-IMPROVE Q: Who are publishers?

A: Publishers are the content providers and Moderators. They facilitate the data
that they would like to publish to the Bitcloud. (For more information regarding Publishers 
please read the publishers page).

* FINISHED Q: How can content creators benefit from Bitcloud?
A: Content creators will benefit from BitCloud by being able to take larger 
cuts from ad revenue on Bitcloud based websites because the added expenses
of the corporate system have been removed. Because Bitcloud is a 
decentralized network, no one power will have complete control over your work.
In the case of a large company, such as YouTube, they have complete control over
the content they host and can remove anything they wish to. This, however, is 
not the case with Bitcloud.

* TO-THINK Q: How can early adopters benefit from Bitcloud?

A: 

* TO-THINK Q: When will Bitcloud be released?

A: Bitcloud will be released upon its completion. We do not know when this will occur.
The development of Bitcloud is completely decentralised and is being done by any and 
all developers willing to help. If you are someone who is willing to help, please find a way 
in which you can do so. We do not just need programmers, but also economists, thinkers, and any other 
people who can and are willing to help. To speed us closer to the release date, pitch in!
