* Publishers

The concept of publishers can be a MAJOR incentive for this
project to be accepted by the information related industries.

We have a real, huge potential in every single industrial field related
to content providing. We can easily attract film industries, music
industries, game industries, ISPs, advertisers, news agencies,
non-profit organizations, individual content creators and much more.
The possibilities are so huge that they are almost unimaginable at this
point in time. We have the ability to finally change the entire copyright system - forever.


There are two things that can happen when this project gets off of the ground:

a) Bitcloud could become another geek p2p protocol that is only used by people that won't
contribute to our economy.
b) Bitcloud could go mainstream. It could be the next revolution as iTunes 
was to the music industry. If we succeed, we are talking about the "entire world" using
our system to interchange information, trade information, and correctly categorize information.

If you look at current p2p systems, specially Kademlia (eMule),
the search results are a total mess. Repeated content, corrupted
content, fake content, incorrectly categorized content, illegal content,
etc. It is absolutely crucial that we design Bitcloud in a way that 
prevents these things from happening. By using publishers, we will be avoiding 
some of these issues that because the publishers are actually human beings looking 
for good quality.

Bitcloud is constructed by the integration of an inter-dependant chain
of modules and plugins, each one having its own BCL (laws).

For example, there are the fundamental modules of routing, storage, and
goverment. From there on, a complete set of plugins can be constructed.

Each plugin will allow publishers to create sub-nets. In the case of the
cloud module (the first and most important one) the publishers create a
sub-net with only the content moderated by them. Collaboration between
publishers is possible.

Examples:

- Cloud plubishers: a publisher does have a collection of files approved. For
  example, a film company, a music store, a software provider, etc.
- A social plugin, like Facebook, Twitter, or Google+. Any publisher will have an 
  independent social sub-net, so it is possible to create
  different social nets each one specialized under the rules of the
  particular publisher.
- A wiki plugin. Each publisher will have and moderate its own wiki.
- A forum plugin. Each publisher will moderate and establish the rules
  of his own forum.
- A market plugin. Each publisher will be in charge of one store or
  collection of stores and will moderate sellers and customers.

Now, the important thing to remember here is that nodes CAN select any
publishers as they wish, and optimize the space and resources for THOSE publishers.
Publishers can pay the nodes or make contracts, or some nodes can just be
owned by the pusblishers.

Also, publishers act as escrow agents to facilitate transactions between the
consumers of the content and the nodes when there are some paid services that
need to be made.

In this model, all content is encrypted both for transit and encrypted by a
nonce key until payment is verified by the escrow agent; at which time, a key
exchange mediated by the publisher occurs, the content is unlocked and the
node receives payment.

Publishers have a toolset allowing them to automatically track whether content
has been delivered, whether payment has been completed, and automatically
notify both parties to a transaction that it has been completed successfully.


The possibilities are endless. We can virtually replace every single
major layer of the actual Internet in a decentralized way by using this system containing publishers.


How can a company or corporation want to enter into ourstructure if they Can't 
moderate and take control of the content they provide? This is why we propose the Publisher System.

*** Reasons for using the Publisher System:


1) Low quality content: repeated with small variation, corrupted, illegal,
   incorrectly categorized, etc.
2) Sometimes, specially for non-profit organizations, their content will not
   be ranked apropiatelly and cannot compete against stupid videos which are
   less important for humanity but most fool people want to see, so they will
   be removed when space is over. Most artists will be against this too.
3) You are now centralizing power in botnets that will constantly going to be
   run to rank certain videos, and consume most of the bandwidth resources.
4) No motivation for artists and industries to enter a non-moderated system
   with low quality.
5) There could be legal issues because all nodes can be blamed to contain
   parts of illegal content (it doesn't matter if they are stored encrypted
   because the content is plublicily accessible anyway).
