#include <stdio.h>
#include "bitcloud.h"

#include "nodepool_sql.h"

sqlite3 *nodepool;

/*
 Opens the nodepool db.
 If it doesn't exist, it creates all the necessary tables.
*/

BCError bc_open_nodepool (const char* filename)
{
  int rc;
  char *err;

  rc = sqlite3_open_v2(filename, &nodepool, SQLITE_OPEN_READWRITE, NULL);
  if (rc) { /* file doesn't exist yet or is readonly */
    sqlite3_close (nodepool);
    rc = sqlite3_open(filename, &nodepool);
    if (rc) {
      sqlite3_close (nodepool);
      nodepool = NULL;
      bc_log(BC_DB_ERROR,
             "could not create the db: %s",
             sqlite3_errmsg(nodepool));
      return (BC_DB_ERROR);
    }
    /* Create all the tables in the nodepool.sql file. nodepool_sql.h was
       generated by xxd utility in the Makefile to include the SQL source into
       the executable. */
    nodepool_sql[nodepool_sql_len] = 0; /* <-- because xxd doesn't end the
                                           string in NULL. Look Makefile. */
    rc = sqlite3_exec (nodepool, (const char*)nodepool_sql,NULL,NULL, &err);
    if (rc != SQLITE_OK) {
      sqlite3_free (err);
      sqlite3_close (nodepool);
      remove (filename);
      nodepool = NULL;
      bc_log (BC_DB_ERROR, "%s", err);
      return (BC_DB_ERROR);
    }
    bc_log (BC_OK, "Nodepool created.");
  }

  return BC_OK;
}



/* general authorization callback function for sqlite */

BCError bc_auth (void *user_data,
                 int event_code,
                 const char *event_spec,
                 const char *event_spec2,
                 const char *db_name,
                 const char *trigger)
{
  switch (event_code) {
    default:
      return SQLITE_DENY;
    }
  return SQLITE_DENY;
}

BCError bc_register_node (BCNode *node)
{
  if (!node) return BC_BAD_DATA;


  return 0;
}

void bc_log (BCError error, char *msg, ...)
{
  va_list args;
  va_start(args, msg);
  if (error!=BC_OK) {
    fprintf (stderr, "ERROR %d: ", error);
  }
  vfprintf (stderr, msg, args);
  fprintf (stderr, "\n");
  va_end(args);

  if (nodepool) {
    /* TODO: insert log into the nodepool */
  }
}
